### ISSUE TITLE
Search result's date is not getting styled

### ISSUE THREAD

**Issue by FlameFractal** [chinchang/super-search#9]

**Comment by sunbliss** [comment]
@FlameFractal This is happening because there is a missing 'super-' in line99 of the javascript code.
If you change it to `return '<li><a href="' + post.link + '">' + post.title + '<span class="super-search__result-date">' + d.toUTCString().replace(/.*(\d{2})\s+(\w{3})\s+(\d{4}).*/,'$2 $1, $3') + '</span></a></li>';` the date will render as it should.
I have already reported it to the op, but I am afraid he closed the issue without correcting the code.
You can see it implemented in this code for the revised version of one of my jekyll website templates [Photorama revised](https://github.com/sunbliss/photor)

**Comment by FlameFractal** [comment]
Yes, I figured that out. You can see in the reference commit above, I've corrected the code and submitted a pull request for the same.
Thanks anyways!

**Comment by chinchang** [comment]
fixed now in 0.0.5
